@extends('layouts.app')
@section('title','Live Crypto Markets — Alpha Block Solutions')
@section('content')
@php
    $formatPrice = static fn ($value) => is_numeric($value) ? '$'.number_format((float) $value, (float) $value < 1 ? 4 : 2) : '—';
    $formatChange = static fn ($value) => is_numeric($value) ? (((float) $value >= 0 ? '+' : '').number_format((float) $value,2).'%') : '—';
@endphp
<section class="page-hero container"><h1>Market intelligence in a <span class="gradient-text">clearer view.</span></h1><p>Public prices and candlestick data are requested from market-data providers and cached briefly to reduce rate-limit pressure.</p></section>
<section class="container market-page-grid">
<article class="panel wide"><div class="panel-title"><div><h3>Core Markets</h3><small class="panel-subtitle">BTC, ETH, SOL, BNB and XRP quoted against USDT</small></div><span class="data-source">Source: {{ ($market['is_live'] ?? false) ? $market['source'] : 'Connecting to providers' }}</span></div><div class="market-table"><div class="table-head"><span>Asset</span><span>Price</span><span>24H</span><span>High</span><span>Low</span><span>Volume</span></div>@foreach($market['core'] as $coin)@php($change=$coin['change_percent'] ?? null)<div class="table-row" data-core-market-row="{{ $coin['symbol'] }}"><span><i class="coin-icon coin-{{ strtolower($coin['base']) }}">{{ substr($coin['base'],0,1) }}</i><b>{{ $coin['pair'] }}</b></span><span data-core-price>{{ $formatPrice($coin['price'] ?? null) }}</span><span data-core-change class="{{ is_numeric($change) ? ((float)$change>=0?'positive':'negative') : 'muted-value' }}">{{ $formatChange($change) }}</span><span data-core-high>{{ $formatPrice($coin['high'] ?? null) }}</span><span data-core-low>{{ $formatPrice($coin['low'] ?? null) }}</span><span data-core-volume>{{ is_numeric($coin['volume'] ?? null) ? '$'.number_format((float)$coin['volume']/1e6,1).'M' : '—' }}</span></div>@endforeach</div></article>
<article class="panel chart-panel wide"><div class="panel-title"><div><h3>BTC/USDT Candlestick Chart</h3><small class="panel-subtitle">Interactive public spot-market candles</small></div><div class="chart-tabs"><button class="active" type="button" data-chart-range="1d">1D</button><button type="button" data-chart-range="7d">7D</button><button type="button" data-chart-range="1m">1M</button><button type="button" data-chart-range="1y">1Y</button><button type="button" data-chart-range="all">ALL</button></div></div><div id="market-chart" class="market-chart large-chart" data-chart-symbol="BTCUSDT"><div class="chart-loading">Connecting to live candles…</div></div></article>
<article class="panel"><h3>Top Liquid Gainers</h3>@forelse($movers['gainers'] as $coin)<div class="mover-row"><span>{{ $loop->iteration }}</span><i>{{ substr($coin['base'],0,1) }}</i><b>{{ $coin['base'] }}</b><small>{{ $formatPrice($coin['price']) }}</small><em class="positive">+{{ number_format($coin['change_percent'],2) }}%</em></div>@empty<div class="content-empty"><b>Live gainers are unavailable.</b><span>The ranking will update when the live market provider reconnects.</span></div>@endforelse</article>
<article class="panel"><h3>Top Liquid Losers</h3>@forelse($movers['losers'] as $coin)<div class="mover-row"><span>{{ $loop->iteration }}</span><i>{{ substr($coin['base'],0,1) }}</i><b>{{ $coin['base'] }}</b><small>{{ $formatPrice($coin['price']) }}</small><em class="negative">{{ number_format($coin['change_percent'],2) }}%</em></div>@empty<div class="content-empty"><b>Live losers are unavailable.</b><span>The ranking will update when the live market provider reconnects.</span></div>@endforelse</article>
<article class="panel"><h3>Global Snapshot</h3><div class="stacked-metrics"><div><small>Total market cap</small><b>{{ is_numeric(data_get($market,'global.total_market_cap')) ? '$'.number_format(data_get($market,'global.total_market_cap')/1e12,2).'T' : '—' }}</b></div><div><small>24H volume</small><b>{{ is_numeric(data_get($market,'global.total_volume')) ? '$'.number_format(data_get($market,'global.total_volume')/1e9,2).'B' : '—' }}</b></div><div><small>Bitcoin dominance</small><b>{{ is_numeric(data_get($market,'global.btc_dominance')) ? number_format(data_get($market,'global.btc_dominance'),2).'%' : '—' }}</b></div><div><small>Active assets</small><b>{{ is_numeric(data_get($market,'global.active_cryptocurrencies')) ? number_format(data_get($market,'global.active_cryptocurrencies')) : '—' }}</b></div></div></article>
<article class="panel"><h3>ABS Market Momentum</h3><div class="gauge giant {{ is_numeric(data_get($market,'sentiment.score')) ? '' : 'gauge-unavailable' }}"><i style="--score:{{ is_numeric(data_get($market,'sentiment.score')) ? data_get($market,'sentiment.score') : 50 }}"></i><strong>{{ is_numeric(data_get($market,'sentiment.score')) ? data_get($market,'sentiment.score') : '—' }}</strong></div><p>{{ data_get($market,'sentiment.method') }}</p></article>
</section>
@endsection
