@extends('admin.layout')
@section('title','Contact & Support Inbox — ABS Admin')
@section('heading','Contact & Support Inbox')
@section('description','Prioritize customer enquiries by operational status, service category and urgency with a clear resolution queue.')
@section('content')
<section class="enterprise-command-bar compact admin-report-command"><div><span class="admin-report-eyebrow">CUSTOMER OPERATIONS · SUPPORT</span><h2>Support workload and service response</h2><p>Track account, Pulse, payment, technical, market-data and security enquiries without losing ownership or priority context.</p></div></section>
<section class="admin-report-kpis support-kpis"><article><span class="report-kpi-icon blue">+</span><div><small>New</small><strong>{{ number_format($summary['new']) }}</strong><em>Unread enquiries</em></div></article><article><span class="report-kpi-icon cyan">◎</span><div><small>Open workload</small><strong>{{ number_format($summary['open']) }}</strong><em>New, open or waiting</em></div></article><article class="{{ $summary['urgent'] ? 'attention' : '' }}"><span class="report-kpi-icon red">!</span><div><small>Urgent attention</small><strong>{{ number_format($summary['urgent']) }}</strong><em>Unresolved priority items</em></div></article><article><span class="report-kpi-icon green">✓</span><div><small>Resolved · 7 days</small><strong>{{ number_format($summary['resolved7']) }}</strong><em>Recent completions</em></div></article></section>
<section class="enterprise-surface enterprise-filter-surface"><div class="filter-surface-head"><div><h2>Queue filters</h2><p>Find a customer or isolate one service and response state.</p></div></div><form method="GET" class="enterprise-filter-grid support-filter-grid"><label>Search<input name="q" value="{{ request('q') }}" placeholder="Name, email or subject"></label><label>Status<select name="status"><option value="">All statuses</option>@foreach(['new','open','waiting','resolved','closed'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label>Category<select name="category"><option value="">All categories</option>@foreach(['account','billing','technical','market_data','security','other'] as $category)<option value="{{ $category }}" @selected(request('category')===$category)>{{ ucwords(str_replace('_',' ',$category)) }}</option>@endforeach</select></label><label>Priority<select name="priority"><option value="">All priorities</option>@foreach(['low','normal','high','urgent'] as $priority)<option value="{{ $priority }}" @selected(request('priority')===$priority)>{{ ucfirst($priority) }}</option>@endforeach</select></label><div class="filter-actions full"><button class="button button-primary">Apply Queue Filters</button><a class="button button-ghost" href="{{ route('admin.enterprise.contacts') }}">Clear</a></div></form></section>
<section class="enterprise-surface no-pad"><div class="enterprise-section-head padded"><div><h2>Support queue</h2><p>{{ number_format($items->total()) }} matching enquiries · newest first</p></div><span class="report-period-chip">SERVICE DESK</span></div><div class="enterprise-table-wrap"><table class="enterprise-table support-queue-table"><thead><tr><th>Reference / Subject</th><th>Customer</th><th>Service area</th><th>Priority</th><th>Status</th><th>Received</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><b>#{{ $item->id }} · {{ $item->subject }}</b><small>{{ \Illuminate\Support\Str::limit($item->message,90) }}</small></td><td><b>{{ $item->name }}</b><small>{{ $item->email }}</small></td><td>{{ ucwords(str_replace('_',' ',$item->category)) }}</td><td><span class="admin-status {{ $item->priority==='urgent'?'danger':($item->priority==='high'?'warn':'muted') }}">{{ ucfirst($item->priority) }}</span></td><td><span class="admin-status {{ in_array($item->status,['resolved','closed'])?'good':($item->status==='new'?'warn':'info') }}">{{ ucfirst($item->status) }}</span></td><td><b>{{ $item->created_at?->format('d M Y · H:i') }}</b><small>{{ $item->created_at?->diffForHumans() }}</small></td><td><a class="enterprise-row-action" href="{{ route('admin.enterprise.contacts.show',$item) }}">Review →</a></td></tr>@empty<tr><td colspan="7"><div class="admin-empty-report"><span>✓</span><h3>No matching support items</h3><p>The selected queue has no unresolved customer enquiries.</p></div></td></tr>@endforelse</tbody></table></div><div class="enterprise-pagination">{{ $items->links() }}</div></section>
@endsection
