@extends('admin.layout')
@section('title','Newsletter Subscribers — ABS Admin')
@section('heading','Newsletter Audience')
@section('description','Understand audience growth, active reach, subscription state and individual market-update preferences.')
@section('content')
<section class="enterprise-command-bar compact admin-report-command"><div><span class="admin-report-eyebrow">COMMUNICATIONS · AUDIENCE</span><h2>Newsletter reach and subscriber control</h2><p>Review active delivery reach, recent audience growth, consent state and content preferences without exposing application secrets.</p></div><a class="button button-ghost" href="{{ route('admin.enterprise.emails') }}">Email Delivery Health</a></section>
<section class="admin-report-kpis support-kpis"><article><span class="report-kpi-icon blue">Σ</span><div><small>Total subscribers</small><strong>{{ number_format($summary['total']) }}</strong><em>Complete audience</em></div></article><article><span class="report-kpi-icon green">✓</span><div><small>Active reach</small><strong>{{ number_format($summary['active']) }}</strong><em>Eligible for delivery</em></div></article><article><span class="report-kpi-icon muted">−</span><div><small>Unsubscribed</small><strong>{{ number_format($summary['unsubscribed']) }}</strong><em>Consent withdrawn</em></div></article><article><span class="report-kpi-icon violet">+</span><div><small>New · 30 days</small><strong>{{ number_format($summary['new30']) }}</strong><em>Recent audience growth</em></div></article></section>
<section class="enterprise-surface enterprise-filter-surface"><div class="filter-surface-head"><div><h2>Audience filters</h2><p>Locate a subscriber or review one consent state.</p></div></div><form method="GET" class="enterprise-filter-grid newsletter-filter-grid"><label>Email search<input type="search" name="q" value="{{ request('q') }}" placeholder="customer@example.com"></label><label>Subscription status<select name="status"><option value="">All subscribers</option><option value="active" @selected(request('status')==='active')>Active</option><option value="unsubscribed" @selected(request('status')==='unsubscribed')>Unsubscribed</option></select></label><div class="filter-actions"><button class="button button-primary">Apply Filters</button><a class="button button-ghost" href="{{ route('admin.enterprise.newsletters') }}">Clear</a></div></form></section>
<section class="enterprise-surface no-pad"><div class="enterprise-section-head padded"><div><h2>Subscriber register</h2><p>{{ number_format($items->total()) }} matching audience records</p></div><span class="report-period-chip">NEWSLETTER</span></div><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>Subscriber</th><th>Status</th><th>Preferences</th><th>Confirmed</th><th>Joined</th><th>Control</th></tr></thead><tbody>@forelse($items as $item)<tr><td><b>{{ $item->email }}</b><small>Subscriber #{{ $item->id }}</small></td><td><span class="admin-status {{ $item->status==='active'?'good':'muted' }}">{{ ucfirst($item->status) }}</span></td><td><small>{{ implode(', ', collect($item->preferences ?: [])->mapWithKeys(fn($v,$k)=>[is_int($k)?$v:$k=>is_int($k)?true:$v])->filter()->keys()->map(fn($v)=>ucwords(str_replace('_',' ',$v)))->all()) ?: 'Default market updates' }}</small></td><td>{{ $item->confirmed_at?->format('d M Y · H:i') ?: 'Not confirmed' }}</td><td><b>{{ $item->created_at?->format('d M Y') }}</b><small>{{ $item->created_at?->diffForHumans() }}</small></td><td><form method="POST" action="{{ route('admin.enterprise.newsletters.update',$item) }}" class="admin-inline-control">@csrf @method('PUT')<select name="status">@foreach(['active','unsubscribed'] as $status)<option value="{{ $status }}" @selected($item->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="button button-ghost button-small">Save</button></form></td></tr>@empty<tr><td colspan="6"><div class="admin-empty-report"><span>✉</span><h3>No matching subscribers</h3><p>Clear the filters to review the complete audience.</p></div></td></tr>@endforelse</tbody></table></div><div class="enterprise-pagination">{{ $items->links() }}</div></section>
@endsection
