@extends('admin.layout')
@section('title','Pulse Subscriptions & Expiry')
@section('heading','Subscriptions & Expiry')
@section('content')
<section class="enterprise-command-bar compact"><div><h2>Pulse subscription control center</h2><p>Track active plans, trials, upcoming expiries, expired access and users who have not yet received a Pulse plan.</p></div><a class="button button-primary" href="{{ route('admin.pulse.plans') }}">Manage plans</a></section>
<section class="enterprise-kpi-grid six">@foreach(['Active'=>$summary['active'],'Trial'=>$summary['trial'],'Expiring ≤7d'=>$summary['expiring7'],'Expiring ≤30d'=>$summary['expiring30'],'Expired'=>$summary['expired'],'Unassigned'=>$summary['unassigned']] as $label=>$value)<article class="enterprise-kpi {{ str_contains($label,'Expir')?'attention':'' }}"><small>{{ $label }}</small><strong>{{ number_format($value) }}</strong></article>@endforeach</section>

<section class="enterprise-surface enterprise-filter-surface"><form method="GET" class="enterprise-filter-grid subscriptions"><label>Search<input name="q" value="{{ request('q') }}" placeholder="Name or email"></label><label>Plan<select name="plan"><option value="">All plans</option>@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected((string)request('plan')===(string)$plan->id)>{{ $plan->name }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">All</option>@foreach(['pending','active','suspended','expired','revoked'] as $x)<option value="{{ $x }}" @selected(request('status')===$x)>{{ ucfirst($x) }}</option>@endforeach</select></label><label>Expiry<select name="expiry"><option value="">Any</option><option value="7" @selected(request('expiry')==='7')>Next 7 days</option><option value="30" @selected(request('expiry')==='30')>Next 30 days</option><option value="expired" @selected(request('expiry')==='expired')>Expired</option><option value="none" @selected(request('expiry')==='none')>No expiry</option></select></label><div class="filter-actions"><button class="button button-primary">Apply</button><a class="button button-ghost" href="{{ route('admin.pulse.access') }}">Clear</a></div></form></section>

<section class="enterprise-surface no-pad"><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>User</th><th>Plan</th><th>Status</th><th>Starts</th><th>Expires</th><th>Remaining</th><th>Last login</th><th></th></tr></thead><tbody>
@forelse($users as $user)
@php $access=$user->pulseAccess; $expired=$access?->ends_at&&$access->ends_at->isPast(); $days=$access?->ends_at?now()->startOfDay()->diffInDays($access->ends_at->copy()->startOfDay(),false):null; @endphp
<tr><td><a href="{{ route('admin.users.show',$user) }}"><b>{{ $user->name }}</b></a><small>{{ $user->email }}</small></td><td>{{ $access?->plan?->name ?? 'Not assigned' }}</td><td><span class="admin-status {{ $access?->isActive()?'good':($expired?'danger':'muted') }}">{{ $access?->status?ucfirst($access->status):'None' }}</span></td><td>{{ $access?->starts_at?->format('d M Y') ?? '—' }}</td><td>{{ $access?->ends_at?->format('d M Y') ?? 'Open-ended' }}</td><td>@if($days!==null)<span class="admin-status {{ $days<0?'danger':($days<=7?'warn':'good') }}">{{ $days<0?abs($days).'d expired':$days.'d' }}</span>@else—@endif</td><td>{{ $user->last_login_at?->diffForHumans() ?? 'Never' }}</td><td><a class="enterprise-row-action" href="{{ route('admin.users.show',$user) }}">Manage →</a></td></tr>
@empty<tr><td colspan="8">No users match the selected subscription filters.</td></tr>@endforelse
</tbody></table></div><div class="enterprise-pagination">{{ $users->links() }}</div></section>
@endsection
