@extends('admin.layout')
@section('title','Pulse Operations Center')
@section('heading','Pulse Operations Center')
@section('description','Live operational state for customer access, scanner activity, active signals, execution protection and auditable system actions.')
@section('content')
<section class="enterprise-command-bar compact"><div><span class="admin-report-eyebrow">PULSE CONTROL ROOM · CURRENT STATE</span><h2>Live operational administration</h2><p>Use this page for current workload and exceptions. Use the Executive Dashboard and Strategy Intelligence for historical charts, outcome trends and investor reporting.</p></div><div class="admin-actions"><a class="button button-primary" href="{{ route('admin.dashboard') }}">Executive Analytics</a><a class="button button-ghost" href="{{ route('admin.pulse.settings') }}">Safety Controls</a><a class="button button-ghost" href="{{ route('pulse.dashboard') }}">Open Member Pulse</a></div></section>
<section class="admin-purpose-card"><div><span class="purpose-label">OPERATIONAL PURPOSE</span><h2>Current exceptions before historical performance</h2><p>This control room shows whether Pulse is available and protected right now. Scanner runs create qualified opportunities; validations establish outcomes; execution records exist only after customer-authorized trade activity.</p></div><div class="admin-purpose-list"><div><i>1</i><span>Check active customer and signal workload</span></div><div><i>2</i><span>Escalate any unconfirmed trade protection</span></div><div><i>3</i><span>Trace recent scanner, trade and audit activity</span></div></div></section>
<section class="enterprise-kpi-grid six">@foreach(['Active users'=>$activeUsers,'Active signals'=>$activeSignals,'Open activity'=>$openTrades,'Protection review'=>$unprotectedTrades,'Best Signal runs'=>$scannerRunsToday,'Stored realized P&L'=>$realizedPnl] as $label=>$value)<article class="enterprise-kpi {{ $label==='Protection review'&&$value>0?'attention':'' }}"><small>{{ $label }}</small><strong>{{ is_float($value)?number_format($value,2):number_format($value) }}</strong></article>@endforeach</section>
<section class="enterprise-quick-links"><a href="{{ route('admin.pulse.intelligence') }}"><b>Strategy Intelligence</b><span>Selected and all-time performance evidence</span></a><a href="{{ route('admin.pulse.signals') }}"><b>Signal Oversight</b><span>Opportunity-to-outcome register</span></a><a href="{{ route('admin.pulse.trades') }}"><b>Execution & Risk</b><span>Customer execution and protection</span></a><a href="{{ route('admin.pulse.strategies') }}"><b>Strategy Controls</b><span>Configure scoring logic</span></a><a href="{{ route('admin.pulse.pairs') }}"><b>Approved Markets</b><span>Manage trading-pair universe</span></a><a href="{{ route('admin.pulse.logs') }}"><b>Audit Trail</b><span>Trace administrator and user actions</span></a></section>
<div class="enterprise-section-grid equal"><section class="enterprise-surface"><div class="enterprise-section-head"><div><h2>Latest scanner runs</h2><p>Newest Pulse scanner activity.</p></div><a href="{{ route('admin.pulse.signals') }}">Signals →</a></div><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>User</th><th>Status</th><th>TF</th><th>Pairs</th><th>Signals</th><th>Completed</th></tr></thead><tbody>@forelse($latestRuns as $run)<tr><td>{{ $run->user?->email ?? 'System' }}</td><td>{{ strtoupper($run->status) }}</td><td>{{ $run->timeframe }}</td><td>{{ $run->pairs_scanned }}</td><td>{{ $run->signals_created }}</td><td>{{ $run->completed_at?->diffForHumans() ?? 'Running' }}</td></tr>@empty<tr><td colspan="6">No scanner activity yet.</td></tr>@endforelse</tbody></table></div></section><section class="enterprise-surface"><div class="enterprise-section-head"><div><h2>Latest trade records</h2><p>Newest Pulse trade activity.</p></div><a href="{{ route('admin.pulse.trades') }}">Trades →</a></div><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>User</th><th>Market</th><th>Status</th><th>Mode</th><th>Protection</th><th>P&L</th></tr></thead><tbody>@forelse($latestTrades as $trade)<tr><td>{{ $trade->user?->email }}</td><td>{{ $trade->symbol }}</td><td>{{ strtoupper(str_replace('_',' ',$trade->status)) }}</td><td>{{ strtoupper($trade->environment) }}</td><td>{{ strtoupper(str_replace('_',' ',$trade->protection_status)) }}</td><td>{{ number_format((float)$trade->realized_pnl,4) }}</td></tr>@empty<tr><td colspan="6">No trade records yet.</td></tr>@endforelse</tbody></table></div></section></div>
<section class="enterprise-surface"><div class="enterprise-section-head"><div><h2>Latest audit events</h2><p>Most recent administrative and Pulse security-sensitive actions.</p></div><a href="{{ route('admin.pulse.logs') }}">Complete audit log →</a></div><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Entity</th><th>Environment</th></tr></thead><tbody>@forelse($latestLogs as $log)<tr><td>{{ $log->created_at?->format('d M H:i:s') }}</td><td>{{ $log->user?->email ?? 'System' }}</td><td>{{ $log->action }}</td><td>{{ $log->entity_type }} {{ $log->entity_id }}</td><td>{{ strtoupper($log->environment ?? '—') }}</td></tr>@empty<tr><td colspan="5">No audit events yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
