@extends('admin.layout')
@section('title','Pulse Operations Center')
@section('heading','Pulse Operations Center')
@section('content')
<section class="enterprise-command-bar compact"><div><h2>Live operational administration</h2><p>Monitor scanner activity, active signals, open positions, protection status, trading records and audit activity.</p></div><div class="admin-actions"><a class="button button-primary" href="{{ route('admin.pulse.access') }}">Subscriptions</a><a class="button button-ghost" href="{{ route('admin.pulse.settings') }}">Controls</a><a class="button button-ghost" href="{{ route('pulse.dashboard') }}">Open Pulse</a></div></section>
<section class="enterprise-kpi-grid six">@foreach(['Active users'=>$activeUsers,'Active signals'=>$activeSignals,'Open activity'=>$openTrades,'Protection review'=>$unprotectedTrades,'Scans today'=>$scannerRunsToday,'Stored realized P&L'=>$realizedPnl] as $label=>$value)<article class="enterprise-kpi {{ $label==='Protection review'&&$value>0?'attention':'' }}"><small>{{ $label }}</small><strong>{{ is_float($value)?number_format($value,2):number_format($value) }}</strong></article>@endforeach</section>
<section class="enterprise-quick-links"><a href="{{ route('admin.pulse.intelligence') }}"><b>Signal Intelligence</b><span>Validate signal quality and learning evidence</span></a><a href="{{ route('admin.pulse.signals') }}"><b>Signals</b><span>Review generated signal status</span></a><a href="{{ route('admin.pulse.trades') }}"><b>Trades</b><span>Review exchange-linked activity</span></a><a href="{{ route('admin.pulse.strategies') }}"><b>Strategies</b><span>Configure scoring logic</span></a><a href="{{ route('admin.pulse.pairs') }}"><b>Markets</b><span>Manage approved trading pairs</span></a><a href="{{ route('admin.pulse.logs') }}"><b>Audit</b><span>Trace administrator and user actions</span></a></section>
<div class="enterprise-section-grid equal"><section class="enterprise-surface"><div class="enterprise-section-head"><div><h2>Latest scanner runs</h2><p>Newest Pulse scanner activity.</p></div><a href="{{ route('admin.pulse.signals') }}">Signals →</a></div><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>User</th><th>Status</th><th>TF</th><th>Pairs</th><th>Signals</th><th>Completed</th></tr></thead><tbody>@forelse($latestRuns as $run)<tr><td>{{ $run->user?->email ?? 'System' }}</td><td>{{ strtoupper($run->status) }}</td><td>{{ $run->timeframe }}</td><td>{{ $run->pairs_scanned }}</td><td>{{ $run->signals_created }}</td><td>{{ $run->completed_at?->diffForHumans() ?? 'Running' }}</td></tr>@empty<tr><td colspan="6">No scanner activity yet.</td></tr>@endforelse</tbody></table></div></section><section class="enterprise-surface"><div class="enterprise-section-head"><div><h2>Latest trade records</h2><p>Newest Pulse trade activity.</p></div><a href="{{ route('admin.pulse.trades') }}">Trades →</a></div><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>User</th><th>Market</th><th>Status</th><th>Mode</th><th>Protection</th><th>P&L</th></tr></thead><tbody>@forelse($latestTrades as $trade)<tr><td>{{ $trade->user?->email }}</td><td>{{ $trade->symbol }}</td><td>{{ strtoupper(str_replace('_',' ',$trade->status)) }}</td><td>{{ strtoupper($trade->environment) }}</td><td>{{ strtoupper(str_replace('_',' ',$trade->protection_status)) }}</td><td>{{ number_format((float)$trade->realized_pnl,4) }}</td></tr>@empty<tr><td colspan="6">No trade records yet.</td></tr>@endforelse</tbody></table></div></section></div>
<section class="enterprise-surface"><div class="enterprise-section-head"><div><h2>Latest audit events</h2><p>Most recent administrative and Pulse security-sensitive actions.</p></div><a href="{{ route('admin.pulse.logs') }}">Complete audit log →</a></div><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Entity</th><th>Environment</th></tr></thead><tbody>@forelse($latestLogs as $log)<tr><td>{{ $log->created_at?->format('d M H:i:s') }}</td><td>{{ $log->user?->email ?? 'System' }}</td><td>{{ $log->action }}</td><td>{{ $log->entity_type }} {{ $log->entity_id }}</td><td>{{ strtoupper($log->environment ?? '—') }}</td></tr>@empty<tr><td colspan="5">No audit events yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
