@extends('admin.layout')
@section('title','Pulse Audit Trail')
@section('heading','Audit Trail')
@section('description','Trace administrator, customer, system and exchange-sensitive activity with date, actor and environment reporting.')
@section('content')
<section class="enterprise-command-bar compact admin-report-command"><div><span class="admin-report-eyebrow">GOVERNANCE · TRACEABILITY</span><h2>Administrative and Pulse activity evidence</h2><p>Reporting period <b>{{ $from->format('d M Y') }}</b> to <b>{{ $to->format('d M Y') }}</b>. Context remains available for investigation without overwhelming the main register.</p></div></section>
<section class="admin-report-kpis cms-kpis"><article><span class="report-kpi-icon blue">Σ</span><div><small>Total events</small><strong>{{ number_format($summary['total']) }}</strong><em>Selected reporting period</em></div></article><article><span class="report-kpi-icon violet">A</span><div><small>Administrator events</small><strong>{{ number_format($summary['administrators']) }}</strong><em>Privileged activity</em></div></article><article><span class="report-kpi-icon cyan">⚙</span><div><small>System events</small><strong>{{ number_format($summary['system']) }}</strong><em>Automated activity</em></div></article><article><span class="report-kpi-icon gold">L</span><div><small>Live environment</small><strong>{{ number_format($summary['live']) }}</strong><em>Production-sensitive events</em></div></article><article class="{{ $summary['security']?'attention':'' }}"><span class="report-kpi-icon red">!</span><div><small>Security-related</small><strong>{{ number_format($summary['security']) }}</strong><em>Login, password or security</em></div></article></section>
<section class="enterprise-surface enterprise-filter-surface"><div class="filter-surface-head"><div><h2>Audit filters</h2><p>Search action names and narrow by actor, date or exchange environment.</p></div></div><form method="GET" class="enterprise-filter-grid audit-filter-grid"><label>From date<input type="date" name="from" value="{{ $from->toDateString() }}"></label><label>To date<input type="date" name="to" value="{{ $to->toDateString() }}"></label><label>Action contains<input name="action" value="{{ request('action') }}" placeholder="admin.signal, login..."></label><label>Actor<input name="user" value="{{ request('user') }}" placeholder="Name or email"></label><label>Environment<select name="environment"><option value="">All environments</option><option value="testnet" @selected(request('environment')==='testnet')>Practice</option><option value="live" @selected(request('environment')==='live')>Live</option></select></label><div class="filter-actions"><button class="button button-primary">Apply Filters</button><a class="button button-ghost" href="{{ route('admin.pulse.logs') }}">Reset to 7 Days</a></div></form></section>
<section class="enterprise-surface no-pad"><div class="enterprise-section-head padded"><div><h2>Audit event register</h2><p>{{ number_format($logs->total()) }} matching records · newest first</p></div><span class="report-period-chip">IMMUTABLE CONTEXT</span></div><div class="enterprise-table-wrap"><table class="enterprise-table audit-event-table"><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Entity</th><th>Environment</th><th>Network</th><th>Evidence</th></tr></thead><tbody>@forelse($logs as $log)<tr><td><b>{{ $log->created_at?->format('d M Y · H:i:s') }}</b><small>{{ $log->created_at?->diffForHumans() }}</small></td><td><b>{{ $log->user?->name ?? 'System' }}</b><small>{{ $log->user?->email ?? 'Automated process' }}</small></td><td><code class="audit-action-code">{{ $log->action }}</code></td><td><b>{{ class_basename($log->entity_type ?: '—') }}</b><small>{{ $log->entity_id ? '#'.$log->entity_id : 'No entity ID' }}</small></td><td><span class="admin-status {{ $log->environment==='live'?'warn':($log->environment==='testnet'?'info':'muted') }}">{{ strtoupper($log->environment ?? 'SYSTEM') }}</span></td><td><b>{{ $log->ip_address ?? '—' }}</b></td><td><details class="admin-reference-list"><summary>View context</summary><pre>{{ json_encode($log->context,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre></details></td></tr>@empty<tr><td colspan="7"><div class="admin-empty-report"><span>≡</span><h3>No matching audit events</h3><p>Change the date range or clear the current filters.</p></div></td></tr>@endforelse</tbody></table></div><div class="enterprise-pagination">{{ $logs->links() }}</div></section>
@endsection
