@extends('admin.layout')
@section('title','Pulse Plans & Entitlements')
@section('heading','Plans & Entitlements')
@section('content')
<section class="enterprise-command-bar compact"><div><h2>Commercial plan configuration</h2><p>Create and maintain Pulse memberships from one place. Control customer visibility, payment eligibility, duration, usage limits, Pulse feature modules, execution permissions and available strategies.</p></div><div class="enterprise-command-actions"><a class="button button-ghost" href="{{ route('admin.pulse.memberships') }}">Memberships & payments</a><a class="button button-ghost" href="{{ route('admin.pulse.access') }}">View subscriptions</a></div></section>

<section class="enterprise-surface no-pad"><div class="enterprise-table-wrap"><table class="enterprise-table"><thead><tr><th>Plan</th><th>Type</th><th>Customer visibility</th><th>Price / term</th><th>Capabilities</th><th>Assigned</th><th>Active</th><th>Expiring ≤30d</th></tr></thead><tbody>@forelse($plans as $plan)<tr><td><b>{{ $plan->name }}</b><small>{{ $plan->slug }}</small></td><td><span class="admin-status {{ $plan->is_trial?'warn':'good' }}">{{ $plan->is_trial?'Trial':'Membership' }}</span></td><td><b>{{ $plan->is_public && !$plan->is_trial ? 'Published' : ($plan->is_trial ? 'Banner only' : 'Hidden') }}</b><small>{{ $plan->request_enabled?'Requests enabled':'Requests disabled' }}</small></td><td>{{ $plan->currency }} {{ number_format((float)$plan->monthly_price,2) }}<small>{{ $plan->access_days }} days</small></td><td>{{ collect($plan->capabilityMatrix())->where('enabled',true)->count() }}/{{ count(\App\Models\PulsePlan::CAPABILITIES) }}</td><td>{{ $plan->assigned_count }}</td><td>{{ $plan->active_count }}</td><td>{{ $plan->expiring_count }}</td></tr>@empty<tr><td colspan="8">No plans configured.</td></tr>@endforelse</tbody></table></div></section>

<details class="enterprise-surface enterprise-plan-editor" open><summary><div><h2>Create a new Pulse plan</h2><p>Define a new package, entitlement matrix and operating limits.</p></div><span>Open editor</span></summary><form method="POST" action="{{ route('admin.pulse.plans.store') }}" class="admin-form-grid">@csrf @include('admin.pulse.partials.plan-fields',['plan'=>null,'strategies'=>$strategies])<div class="full admin-page-actions"><button class="button button-primary">Create plan</button></div></form></details>

@foreach($plans as $plan)
<details class="enterprise-surface enterprise-plan-editor"><summary><div><h2>{{ $plan->name }}</h2><p>{{ $plan->active_count }} active · {{ $plan->assigned_count }} assigned · {{ $plan->expiring_count }} expiring within 30 days</p></div><span>Edit plan</span></summary><form method="POST" action="{{ route('admin.pulse.plans.update',$plan) }}" class="admin-form-grid">@csrf @method('PUT') @include('admin.pulse.partials.plan-fields',['plan'=>$plan,'strategies'=>$strategies])<div class="full admin-page-actions"><button class="button button-primary">Save changes</button></div></form><form method="POST" action="{{ route('admin.pulse.plans.destroy',$plan) }}" class="admin-delete-form">@csrf @method('DELETE')<button class="button button-ghost" onclick="return confirm('Delete this unused plan?')">Delete unused plan</button></form></details>
@endforeach
@endsection
