@extends('layouts.app')
@section('title','Private Member Portal — Alpha Block Solutions')
@section('content')
<section class="page-hero container compact private-heading"><h1>Private Member <span class="gradient-text">Portal</span></h1><p>Secure account reporting visible only to the account holder and authorized ABS administrators.</p></section>
@if($account)
<section class="container private-dashboard">
    <div class="private-summary panel"><div><small>Current Account Value</small><h2>{{ $account->currency }} {{ number_format($account->current_value,2) }}</h2><span>Valuation date: {{ optional($account->valuation_date)->format('d M Y') ?: 'Not recorded' }}</span></div><div><small>Net Contributions</small><strong>{{ $account->currency }} {{ number_format($account->net_contributions,2) }}</strong></div><div><small>Total Profit / Loss</small><strong class="{{ $account->total_profit>=0?'positive':'negative' }}">{{ $account->currency }} {{ number_format($account->total_profit,2) }}</strong></div><div><small>Current Reporting Month</small><strong class="{{ $account->monthly_profit>=0?'positive':'negative' }}">{{ $account->currency }} {{ number_format($account->monthly_profit,2) }}</strong></div></div>
    <article class="panel"><h2>Account Information</h2><p><strong>{{ $account->account_name }}</strong></p><p>{{ $account->notes ?: 'No additional account note has been published.' }}</p><div class="disclaimer">Values reflect the latest account update recorded on the stated valuation date. Contact ABS if any figure needs clarification.</div></article>
    <article class="panel"><h2>Monthly Statements</h2><p>Open a statement to review its reported opening balance, contributions, withdrawals, profit or loss, and closing balance.</p><div class="market-table"><div class="table-head"><span>Month</span><span>Opening</span><span>Profit / Loss</span><span>Closing</span><span>Actions</span></div>@forelse($account->statements as $statement)<div class="table-row"><span>{{ $statement->statement_month->format('F Y') }}</span><span>{{ number_format($statement->opening_balance,2) }}</span><span class="{{ $statement->profit_loss>=0?'positive':'negative' }}">{{ number_format($statement->profit_loss,2) }}</span><span>{{ number_format($statement->closing_balance,2) }}</span><span><a href="{{ route('private.statement',$statement) }}">View statement</a> · <a href="{{ route('private.statement.export',$statement) }}">Download CSV</a></span></div>@empty<div class="content-empty compact-empty"><b>No monthly statement is available yet.</b><span>Published monthly statements will appear here automatically.</span></div>@endforelse</div></article>
    <article class="panel"><h2>Transaction History</h2><p>Only records assigned to this reporting account are visible here.</p><div class="market-table"><div class="table-head"><span>Date</span><span>Type</span><span>Reference</span><span>Description</span><span>Amount</span></div>@forelse($account->transactions as $tx)<div class="table-row"><span>{{ $tx->transaction_date->format('d M Y') }}</span><span>{{ ucfirst($tx->type) }}</span><span>{{ $tx->reference ?: '—' }}</span><span>{{ $tx->description ?: 'No description recorded' }}</span><span>{{ $account->currency }} {{ number_format($tx->amount,2) }}</span></div>@empty<div class="content-empty compact-empty"><b>No transaction has been recorded yet.</b><span>New deposits, withdrawals, fees and performance entries will appear here.</span></div>@endforelse</div></article>
    <div class="disclaimer"><strong>Important:</strong> This portal provides account reporting only. Figures should be reviewed together with the applicable account agreement and risk disclosures.</div>
</section>
@else
<section class="container panel empty-state"><h2>No reporting account has been assigned.</h2><p>Your Private Member Portal is active, but the account record has not been added yet. Contact {{ config('brand.support_email') }} for an access review.</p></section>
@endif
@endsection
