@extends('pulse.layout')
@section('title','Portfolio Activity · ABS Pulse')
@section('heading','Portfolio Activity')
@section('content')
<section class="pi-shell pi-transactions-v1574">
<header class="pi-head"><div><span class="pi-kicker">Private Investor</span><h1>Portfolio Activity</h1><p>Your confirmed capital movements, paid profit and account corrections in one audited ledger.</p></div><a class="pi-btn" href="{{ route('private.index') }}">Portfolio Overview</a></header>
@include('private._tabs')
@if($account && $transactions)
    <div class="pi-grid pi-grid-4">
        <article class="pi-stat"><small>Investment Added</small><strong>{{ $account->currency }} {{ number_format($activitySummary['investment'],2) }}</strong><em>Confirmed capital received</em></article>
        <article class="pi-stat"><small>Capital Withdrawn</small><strong>{{ $account->currency }} {{ number_format($activitySummary['capital_withdrawal'],2) }}</strong><em>Principal returned to you</em></article>
        <article class="pi-stat"><small>Profit Paid</small><strong class="pi-positive">{{ $account->currency }} {{ number_format($activitySummary['profit_paid'],2) }}</strong><em>Profit distributed outside the portfolio</em></article>
        <article class="pi-stat"><small>Losses & Fees</small><strong class="{{ $activitySummary['cost']>0?'pi-negative':'' }}">{{ $account->currency }} {{ number_format($activitySummary['cost'],2) }}</strong><em>Posted deductions</em></article>
    </div>
    @php($activityMax=max(1,max(array_merge($activityChart['deposits'] ?: [0],$activityChart['withdrawals'] ?: [0],array_map('abs',$activityChart['performance'] ?: [0])))))
    <article class="pi-card"><div class="pi-card-head"><div><h2>12-Month Activity</h2><span>Capital received, principal returned and paid/net performance</span></div></div><div class="pi-flow-chart pi-flow-chart-member">@foreach($activityChart['labels'] as $i=>$label)<div class="pi-flow-column"><div class="pi-flow-bars"><i class="deposit" style="height:{{ max(2,($activityChart['deposits'][$i]/$activityMax)*100) }}%"></i><i class="withdrawal" style="height:{{ max(2,($activityChart['withdrawals'][$i]/$activityMax)*100) }}%"></i><i class="performance {{ $activityChart['performance'][$i]<0?'negative':'' }}" style="height:{{ max(2,(abs($activityChart['performance'][$i])/$activityMax)*100) }}%"></i></div><small>{{ explode(' ',$label)[0] }}</small></div>@endforeach</div><div class="pi-legend"><span><i class="deposit"></i>Investment</span><span><i class="withdrawal"></i>Capital withdrawn</span><span><i class="performance"></i>Paid / net performance</span></div></article>
    <article class="pi-card"><div class="pi-card-head"><div><h2>Activity Ledger</h2><span>Every posted or corrected financial entry remains visible</span></div></div><div class="pi-table-wrap"><table class="pi-table"><thead><tr><th>Date</th><th>Activity</th><th>Performance Month</th><th>Reference</th><th>Description</th><th>Status</th><th>Amount</th></tr></thead><tbody>@forelse($transactions as $tx)@php($label=match($tx->type){'deposit'=>'Investment','withdrawal'=>'Capital Withdrawal','profit'=>'Profit Paid','loss'=>'Loss','fee'=>'Fee','adjustment'=>'Adjustment',default=>ucfirst($tx->type)})<tr class="{{ $tx->status==='voided'?'is-voided':'' }}"><td>{{ $tx->transaction_date->format('d M Y') }}</td><td>{{ $label }}</td><td>{{ $tx->performance_month?->format('M Y') ?: '—' }}</td><td>{{ $tx->reference ?: '—' }}</td><td>{{ $tx->description ?: '—' }}@if($tx->status==='voided' && $tx->void_reason)<small>Correction: {{ $tx->void_reason }}</small>@endif</td><td><span class="pi-status {{ $tx->status }}">{{ $tx->status==='voided'?'Corrected':ucfirst($tx->status) }}</span></td><td class="{{ $tx->status==='voided'?'pi-muted':(in_array($tx->type,['profit','deposit'])?'pi-positive':(in_array($tx->type,['withdrawal','loss','fee'])?'pi-negative':'')) }}">{{ $account->currency }} {{ number_format($tx->amount,2) }}</td></tr>@empty<tr><td colspan="7">No portfolio activity recorded.</td></tr>@endforelse</tbody></table></div>{{ $transactions->links() }}</article>
    <div class="pi-sensitive-note"><b>How balances work</b><span>Profit Paid is money distributed to you and therefore does not increase your invested principal. Capital Withdrawn is only principal returned. Posted corrections remain visible so the account history stays auditable.</span></div>
@else<div class="pi-empty">Portfolio reporting has not been configured yet.</div>@endif
</section>
@endsection
