@extends('pulse.layout')
@section('title','Pulse Orders & Positions')
@section('heading','Exchange Orders & Positions')
@section('content')
<div class="pulse-page-head"><div><h2>Direct Binance account snapshot</h2><p>This page reads the connected account's current positions, normal open orders and conditional algo orders. It does not invent fallback exchange data.</p></div><div class="pulse-actions"><form method="POST" action="{{ route('pulse.trades.sync') }}">@csrf<button class="pulse-button">Sync Local Trades</button></form><a class="pulse-button secondary" href="{{ route('pulse.orders') }}">Refresh Snapshot</a></div></div>
<?php if ($error): ?>
<div class="pulse-panel"><div class="content-empty"><b>Exchange snapshot unavailable</b><span>{{ $error }}</span><a class="pulse-button secondary" href="{{ route('pulse.binance.index') }}">Review Binance Connection</a></div></div>
<?php else: ?>
<div class="orders-account">
    <?php foreach (['total_wallet_balance'=>'Wallet Balance','available_balance'=>'Available Balance','total_margin_balance'=>'Margin Balance','total_unrealized_profit'=>'Unrealized P&L'] as $key=>$label): ?><div><small>{{ strtoupper($label) }}</small><b class="{{ str_contains($key,'profit') && ($snapshot['account'][$key]??0)<0?'negative':'' }}">{{ number_format((float)($snapshot['account'][$key]??0),4) }} USDT</b></div><?php endforeach; ?>
</div>
<div class="pulse-grid pulse-grid-two" id="open-positions" style="margin-top:14px">
<article class="pulse-panel"><div class="pulse-panel-head"><div><h2>Open Positions</h2></div><span class="pulse-badge environment-{{ $snapshot['environment'] }}">{{ ($snapshot['environment'] ?? 'testnet') === 'live' ? 'LIVE' : 'PRACTICE' }}</span></div><div class="position-grid"><?php $__absForelseEmpty1 = true; foreach ($snapshot['positions']??[] as $position): $__absForelseEmpty1 = false; ?><div class="position-card"><div class="position-card-head"><b>{{ $position['symbol']??'—' }}</b><span>{{ $position['positionSide']??'BOTH' }}</span></div><div class="position-values"><div><small>AMOUNT</small><b>{{ $position['positionAmt']??'—' }}</b></div><div><small>ENTRY</small><b>{{ $position['entryPrice']??'—' }}</b></div><div><small>MARK</small><b>{{ $position['markPrice']??'—' }}</b></div><div><small>LEVERAGE</small><b>{{ $position['leverage']??'—' }}×</b></div><div><small>LIQUIDATION</small><b>{{ $position['liquidationPrice']??'—' }}</b></div><div><small>UNREALIZED</small><b class="{{ ($position['unRealizedProfit']??0)>=0?'positive':'negative' }}">{{ $position['unRealizedProfit']??'—' }}</b></div></div></div><?php endforeach; if ($__absForelseEmpty1): ?><div class="content-empty compact-empty"><b>No open exchange position.</b><span>Binance returned no non-zero USD-M position for this account.</span></div><?php endif; ?></div></article>
<article class="pulse-panel"><div class="pulse-panel-head"><div><small>NORMAL ORDERS</small><h2>Open Entry / Close Orders</h2></div><span>{{ count($snapshot['open_orders']??[]) }}</span></div><div class="pulse-data-table-wrap"><table class="pulse-data-table"><thead><tr><th>Symbol</th><th>Side</th><th>Type</th><th>Price</th><th>Quantity</th><th>Status</th></tr></thead><tbody><?php $__absForelseEmpty2 = true; foreach ($snapshot['open_orders']??[] as $order): $__absForelseEmpty2 = false; ?><tr><td>{{ $order['symbol']??'—' }}</td><td>{{ $order['side']??'—' }}</td><td>{{ $order['type']??'—' }}</td><td>{{ $order['price']??'—' }}</td><td>{{ $order['origQty']??'—' }}</td><td>{{ $order['status']??'—' }}</td></tr><?php endforeach; if ($__absForelseEmpty2): ?><tr><td colspan="6">No open entry or close order is currently reported by Binance.</td></tr><?php endif; ?></tbody></table></div></article>
</div>
<article class="pulse-panel"><div class="pulse-panel-head"><div><small>CONDITIONAL ALGO ORDERS</small><h2>Exchange-side Stop Loss & Take Profit</h2></div><span>{{ count($snapshot['open_algo_orders']??[]) }}</span></div><div class="pulse-data-table-wrap"><table class="pulse-data-table"><thead><tr><th>Algo ID</th><th>Symbol</th><th>Side</th><th>Type</th><th>Trigger</th><th>Status</th><th>Position Side</th></tr></thead><tbody><?php $__absForelseEmpty3 = true; foreach ($snapshot['open_algo_orders']??[] as $order): $__absForelseEmpty3 = false; ?><tr><td>{{ $order['algoId']??'—' }}</td><td>{{ $order['symbol']??'—' }}</td><td>{{ $order['side']??'—' }}</td><td>{{ $order['type']??'—' }}</td><td>{{ $order['triggerPrice']??$order['stopPrice']??'—' }}</td><td>{{ $order['algoStatus']??$order['status']??'—' }}</td><td>{{ $order['positionSide']??'BOTH' }}</td></tr><?php endforeach; if ($__absForelseEmpty3): ?><tr><td colspan="7">No open stop-loss or take-profit order is currently reported by Binance.</td></tr><?php endif; ?></tbody></table></div><div class="pulse-warning"><b>Protection verification</b><span>Pulse stores Binance algo IDs and verifies them during synchronization. Always compare these records with the exchange.</span></div></article>
<?php endif; ?>
@endsection
