<?php
    $filters = (array) ($page['filters'] ?? []);
    $minimumScore = (float) ($filters['min_score'] ?? 70);
?>
<section class="pp-scanner-bottom" data-scan-fragment="bottom">
        <article class="pp-card pp-market-conditions"><h2 class="pp-card-title">Market Conditions</h2><div class="pp-market-icons"><div>@include('pulse.partials.icon', ['name' => 'trend'])<small>Market Bias</small><strong class="pp-positive">{{ $page['market_bias'] }}</strong></div><div>@include('pulse.partials.icon', ['name' => 'coin'])<small>BTC Dominance</small><strong class="pp-positive">{{ $page['btc_dominance'] === null ? '—' : number_format($page['btc_dominance'], 1).'%' }}</strong></div><div>@include('pulse.partials.icon', ['name' => 'pulse'])<small>Volatility</small><strong class="pp-warning">{{ $page['volatility'] }}</strong></div><div>@include('pulse.partials.icon', ['name' => 'info'])<small>Liquidity</small><strong class="pp-positive">{{ $page['liquidity'] }}</strong></div></div><div class="pp-market-note">@include('pulse.partials.icon', ['name' => 'check']) <span>Conditions support selective participation; prioritize liquidity and configured risk limits.</span></div></article>
        <article class="pp-card pp-scan-quality"><h2 class="pp-card-title">Scan Quality</h2><div class="pp-quality-list"><div><span>Pairs Assessed</span><span>{{ $page['pairs_assessed'] }} / {{ $page['pairs_monitored'] }}</span><span class="pp-quality-bar"><i style="width:{{ $page['scan_coverage'] }}%"></i></span>@include('pulse.partials.icon', ['name' => 'check'])</div><div><span>Data Freshness</span><span>{{ $page['data_freshness'] }}</span><span class="pp-quality-bar"><i style="width:100%"></i></span>@include('pulse.partials.icon', ['name' => 'check'])</div><div><span>Insufficient Data</span><span>{{ $page['insufficient_data'] }}</span><span class="pp-quality-bar"><i style="width:100%"></i></span>@include('pulse.partials.icon', ['name' => 'check'])</div><div><span>Last Full Scan</span><span>{{ $page['latest_run']?->completed_at?->diffForHumans() ?? 'not yet' }}</span><span></span>@include('pulse.partials.icon', ['name' => 'check'])</div></div></article>
        <article class="pp-card pp-saved-view"><h2 class="pp-card-title">Saved Scanner View</h2><div class="pp-saved-body"><span class="pp-saved-icon">@include('pulse.partials.icon', ['name' => 'briefcase'])</span><div class="pp-saved-copy"><strong>Selected Market Scan</strong><span>{{ $page['selected_pairs'] }} selected markets · {{ $page['strategy_options']->count() }} strategies · score ≥ {{ number_format($minimumScore, 0) }}</span></div><div class="pp-saved-actions"><button class="pp-button" type="button" data-scan-load>Load View</button><button class="pp-button primary" type="button" data-scan-save>Save Current</button></div></div></article>
    </section>
