import 'package:flutter/material.dart';

import '../core/api_client.dart';
import '../core/app_config.dart';
import '../core/json_tools.dart';
import '../core/session.dart';
import '../core/theme.dart';
import '../widgets/abs_ui.dart';

class AccountNotificationsScreen extends StatefulWidget {
  const AccountNotificationsScreen({super.key});
  @override State<AccountNotificationsScreen> createState() => _AccountNotificationsScreenState();
}

class _AccountNotificationsScreenState extends State<AccountNotificationsScreen> {
  bool loading = true; String? error; List<Map<String,dynamic>> items=[];
  @override void didChangeDependencies(){super.didChangeDependencies();if(loading&&items.isEmpty)_load();}
  Future<void> _load() async {setState((){loading=true;error=null;});try{items=JsonTools.pageItems(await SessionScope.of(context).api.get('/notifications'));}on ApiException catch(e){error=e.message;}finally{if(mounted)setState(()=>loading=false);}}
  Future<void> _read(Map<String,dynamic> item) async {final id=JsonTools.text(item['id'],'');if(id.isEmpty)return;try{await SessionScope.of(context).api.post('/notifications/$id/read');await _load();}on ApiException catch(e){if(mounted)showSnack(context,e.message,error:true);}}
  @override Widget build(BuildContext context)=>AbsPage(title:'Notifications',subtitle:'ABS account and system notifications',actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))],child:loading?const LoadingBlock():error!=null?ErrorBlock(message:error!,onRetry:_load):RefreshIndicator(onRefresh:_load,child:ListView(physics:const AlwaysScrollableScrollPhysics(),children:[
    ...items.map((n){final data=JsonTools.map(n['data']);final unread=n['read_at']==null;final title=JsonTools.text(data['title']??data['subject']??data['type'],'ABS notification');final message=JsonTools.text(data['message']??data['body']??data['text'],'Open for account information.');return Padding(padding:const EdgeInsets.only(bottom:8),child:InkWell(onTap:unread?()=>_read(n):null,borderRadius:BorderRadius.circular(18),child:AbsCard(child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:42,height:42,decoration:BoxDecoration(color:unread?AbsColors.cyan.withValues(alpha:.12):AbsColors.panel2,borderRadius:BorderRadius.circular(12)),child:Icon(unread?Icons.notifications_active_outlined:Icons.notifications_none,color:unread?AbsColors.cyan:AbsColors.muted)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title,style:TextStyle(fontWeight:unread?FontWeight.w900:FontWeight.w700))),if(unread)const StatusChip('NEW',good:true)]),const SizedBox(height:5),Text(message,style:const TextStyle(color:AbsColors.muted,fontSize:12)),const SizedBox(height:6),Text(compactDate(n['created_at']),style:const TextStyle(color:AbsColors.muted,fontSize:10))]))]))));}),
    if(items.isEmpty)const EmptyState(title:'You are all caught up',message:'Account notifications from ABS will appear here.',icon:Icons.notifications_none),
  ])));
}

class NotificationPreferencesScreen extends StatefulWidget {const NotificationPreferencesScreen({super.key});@override State<NotificationPreferencesScreen> createState()=>_NotificationPreferencesScreenState();}
class _NotificationPreferencesScreenState extends State<NotificationPreferencesScreen>{bool loading=true,saving=false;String?error;Map<String,dynamic>prefs={};final labels=const {'signals':'Signal opportunities','trades':'Trade lifecycle','risk':'Risk & protection','market':'Market feed','plan_expiry':'Plan expiry','daily_brief':'Daily brief','system':'System notices'};@override void didChangeDependencies(){super.didChangeDependencies();if(loading&&prefs.isEmpty)_load();}Future<void>_load()async{setState((){loading=true;error=null;});try{prefs=JsonTools.map(JsonTools.at(await SessionScope.of(context).api.get('/notification-preferences'),'data',<String,dynamic>{}));}on ApiException catch(e){error=e.message;}finally{if(mounted)setState(()=>loading=false);}}Future<void>_save()async{setState(()=>saving=true);try{final r=await SessionScope.of(context).api.put('/notification-preferences',body:prefs.map((k,v)=>MapEntry(k,JsonTools.boolean(v))));prefs=JsonTools.map(JsonTools.at(r,'data',prefs));if(mounted)showSnack(context,'Notification preferences updated.');}on ApiException catch(e){if(mounted)showSnack(context,e.message,error:true);}finally{if(mounted)setState(()=>saving=false);}}@override Widget build(BuildContext context)=>AbsPage(title:'Notification Preferences',subtitle:'Choose what ABS surfaces to you',child:loading?const LoadingBlock():error!=null?ErrorBlock(message:error!,onRetry:_load):ListView(children:[AbsCard(child:Column(children:labels.entries.map((e)=>SwitchListTile(contentPadding:EdgeInsets.zero,value:JsonTools.boolean(prefs[e.key],true),title:Text(e.value,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(_subtitle(e.key),style:const TextStyle(color:AbsColors.muted,fontSize:11)),onChanged:(v)=>setState(()=>prefs[e.key]=v))).toList())),const SizedBox(height:14),ElevatedButton(onPressed:saving?null:_save,child:Text(saving?'Saving...':'Save preferences'))]));String _subtitle(String k)=>switch(k){'signals'=>'New signal and validation updates.','trades'=>'Order, position, TP/SL and close status.','risk'=>'Protection failures, limits and emergency notices.','market'=>'Central ABS price-feed health and market events.','plan_expiry'=>'Membership expiry and entitlement notices.','daily_brief'=>'Optional daily account intelligence summary.','system'=>'Important ABS account and service notices.',_=>'ABS notification'};}

class SessionsScreen extends StatefulWidget {const SessionsScreen({super.key});@override State<SessionsScreen> createState()=>_SessionsScreenState();}
class _SessionsScreenState extends State<SessionsScreen>{bool loading=true;String?error;List<Map<String,dynamic>>sessions=[];@override void didChangeDependencies(){super.didChangeDependencies();if(loading&&sessions.isEmpty)_load();}Future<void>_load()async{setState((){loading=true;error=null;});try{sessions=JsonTools.mapList(JsonTools.at(await SessionScope.of(context).api.get('/auth/sessions'),'data',<dynamic>[]));}on ApiException catch(e){error=e.message;}finally{if(mounted)setState(()=>loading=false);}}Future<void>_revoke(Map<String,dynamic>s)async{if(JsonTools.boolean(s['current'])){showSnack(context,'Use Sign out to end the current session.',error:true);return;}try{await SessionScope.of(context).api.delete('/auth/sessions/${JsonTools.integer(s['id'])}');await _load();}on ApiException catch(e){if(mounted)showSnack(context,e.message,error:true);}}@override Widget build(BuildContext context)=>AbsPage(title:'Active Sessions',subtitle:'Manage ABS API/mobile sign-ins',actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))],child:loading?const LoadingBlock():error!=null?ErrorBlock(message:error!,onRetry:_load):ListView(children:[...sessions.map((s)=>Padding(padding:const EdgeInsets.only(bottom:8),child:AbsCard(child:Row(children:[Icon(JsonTools.boolean(s['current'])?Icons.phone_android:Icons.devices_other,color:JsonTools.boolean(s['current'])?AbsColors.green:AbsColors.cyan),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(JsonTools.text(s['name'],'ABS session'),style:const TextStyle(fontWeight:FontWeight.w800))),if(JsonTools.boolean(s['current']))const StatusChip('CURRENT',good:true)]),const SizedBox(height:4),Text('Created ${compactDate(s['created_at'])} · Last used ${compactDate(s['last_used_at'])}',style:const TextStyle(color:AbsColors.muted,fontSize:10))])),if(!JsonTools.boolean(s['current']))IconButton(onPressed:()=>_revoke(s),icon:const Icon(Icons.logout,color:AbsColors.red),tooltip:'Revoke')])))),if(sessions.isEmpty)const EmptyState(title:'No active sessions',message:'Your authenticated ABS sessions will appear here.',icon:Icons.devices_other)]));}

class RegisteredDevicesScreen extends StatefulWidget {const RegisteredDevicesScreen({super.key});@override State<RegisteredDevicesScreen> createState()=>_RegisteredDevicesScreenState();}
class _RegisteredDevicesScreenState extends State<RegisteredDevicesScreen>{bool loading=true;String?error;List<Map<String,dynamic>>devices=[];@override void didChangeDependencies(){super.didChangeDependencies();if(loading&&devices.isEmpty)_load();}Future<void>_load()async{setState((){loading=true;error=null;});try{devices=JsonTools.mapList(JsonTools.at(await SessionScope.of(context).api.get('/devices'),'data',<dynamic>[]));}on ApiException catch(e){error=e.message;}finally{if(mounted)setState(()=>loading=false);}}Future<void>_remove(Map<String,dynamic>d)async{try{await SessionScope.of(context).api.delete('/devices/${JsonTools.integer(d['id'])}');await _load();}on ApiException catch(e){if(mounted)showSnack(context,e.message,error:true);}}@override Widget build(BuildContext context)=>AbsPage(title:'Registered Devices',subtitle:'Mobile-device registrations known to ABS',actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))],child:loading?const LoadingBlock():error!=null?ErrorBlock(message:error!,onRetry:_load):ListView(children:[...devices.map((d)=>Padding(padding:const EdgeInsets.only(bottom:8),child:AbsCard(child:Row(children:[Icon(JsonTools.text(d['platform'])=='ios'?Icons.phone_iphone:Icons.phone_android,color:AbsColors.cyan),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(JsonTools.text(d['device_name'],'ABS Pulse'),style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:4),Text('${JsonTools.text(d['platform']).toUpperCase()} · App ${JsonTools.text(d['app_version'])} · Seen ${compactDate(d['last_seen_at'])}',style:const TextStyle(color:AbsColors.muted,fontSize:10))])),IconButton(onPressed:()=>_remove(d),icon:const Icon(Icons.delete_outline,color:AbsColors.red),tooltip:'Remove registration')])))),if(devices.isEmpty)const EmptyState(title:'No registered devices',message:'This app registers itself after successful sign-in.',icon:Icons.phone_android)]));}

class PrivateMemberScreen extends StatefulWidget {const PrivateMemberScreen({super.key});@override State<PrivateMemberScreen> createState()=>_PrivateMemberScreenState();}
class _PrivateMemberScreenState extends State<PrivateMemberScreen>{bool loading=true;String?error;Map<String,dynamic>account={};@override void didChangeDependencies(){super.didChangeDependencies();if(loading&&account.isEmpty)_load();}Future<void>_load()async{setState((){loading=true;error=null;});try{account=JsonTools.map(JsonTools.at(await SessionScope.of(context).api.get('/private/account'),'data',<String,dynamic>{}));}on ApiException catch(e){error=e.statusCode==403?'Private Member Portal access is not enabled for this account.':e.message;}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context)=>AbsPage(title:'Private Member Portal',subtitle:'Portfolio account and monthly statements',actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))],child:loading?const LoadingBlock():error!=null?ErrorBlock(message:error!,onRetry:_load):ListView(children:[
    AbsCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.account_balance_outlined,color:AbsColors.gold,size:32),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(JsonTools.text(account['account_name'],'Private Member Account'),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:3),Text('Valuation ${compactDate(account['valuation_date'])}',style:const TextStyle(color:AbsColors.muted,fontSize:11))])),StatusChip(JsonTools.boolean(account['is_active'],true)?'ACTIVE':'INACTIVE',good:JsonTools.boolean(account['is_active'],true))]),const SizedBox(height:14),KeyValueRow('Current value','${JsonTools.text(account['currency'],'USD')} ${number(account['current_value'])}'),KeyValueRow('Net contributions',number(account['net_contributions'])),KeyValueRow('Total profit',number(account['total_profit']),valueColor:pnlColor(account['total_profit'])),KeyValueRow('Monthly profit',number(account['monthly_profit']),valueColor:pnlColor(account['monthly_profit']))])),
    const SizedBox(height:18),const AbsSectionTitle('Monthly statements'),const SizedBox(height:9),...JsonTools.mapList(account['statements']).map((s)=>Padding(padding:const EdgeInsets.only(bottom:8),child:InkWell(onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>PrivateStatementScreen(statementId:JsonTools.integer(s['id']),initial:s))),child:AbsCard(child:Row(children:[const Icon(Icons.receipt_long_outlined,color:AbsColors.cyan),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(JsonTools.text(s['statement_month'],'Monthly statement'),style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:3),Text('Closing ${number(s['closing_balance'])}',style:const TextStyle(color:AbsColors.muted,fontSize:11))])),const Icon(Icons.chevron_right,color:AbsColors.muted)]))))),
    const SizedBox(height:18),const AbsSectionTitle('Transactions'),const SizedBox(height:9),...JsonTools.mapList(account['transactions']).take(30).map((t)=>Padding(padding:const EdgeInsets.only(bottom:8),child:AbsCard(child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(JsonTools.text(t['description']??t['type'],'Portfolio transaction'),style:const TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:3),Text(compactDate(t['transaction_date']),style:const TextStyle(color:AbsColors.muted,fontSize:10))])),Text(number(t['amount']),style:TextStyle(fontWeight:FontWeight.w800,color:pnlColor(t['amount'])))])))),
  ]));}

class PrivateStatementScreen extends StatefulWidget {const PrivateStatementScreen({super.key,required this.statementId,this.initial});final int statementId;final Map<String,dynamic>?initial;@override State<PrivateStatementScreen> createState()=>_PrivateStatementScreenState();}
class _PrivateStatementScreenState extends State<PrivateStatementScreen>{bool loading=true;String?error;Map<String,dynamic>data={};@override void didChangeDependencies(){super.didChangeDependencies();if(loading&&data.isEmpty)_load();}Future<void>_load()async{try{data=JsonTools.map(JsonTools.at(await SessionScope.of(context).api.get('/private/statements/${widget.statementId}'),'data',widget.initial??<String,dynamic>{}));}on ApiException catch(e){error=e.message;data=widget.initial??{};}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context)=>AbsPage(title:'Monthly Statement',subtitle:JsonTools.text(data['statement_month']),child:loading?const LoadingBlock():error!=null&&data.isEmpty?ErrorBlock(message:error!,onRetry:_load):ListView(children:[AbsCard(child:Column(children:[KeyValueRow('Opening balance',number(data['opening_balance'])),KeyValueRow('Contributions',number(data['contributions'])),KeyValueRow('Withdrawals',number(data['withdrawals'])),KeyValueRow('Profit / loss',number(data['profit_loss']),valueColor:pnlColor(data['profit_loss'])),KeyValueRow('Closing balance',number(data['closing_balance']))])),if(JsonTools.text(data['notes'],'').isNotEmpty)...[const SizedBox(height:12),AbsCard(child:Text(JsonTools.text(data['notes'])))] ]));}

class AboutAppScreen extends StatelessWidget {const AboutAppScreen({super.key});@override Widget build(BuildContext context){final session=SessionScope.of(context);return AbsPage(title:'About ABS Pulse',subtitle:'Native Flutter trading intelligence',child:ListView(children:[Center(child:Image.asset('assets/brand/abs-logo-master.png',width:110,height:110)),const SizedBox(height:18),const Text('Alpha Block Solutions',textAlign:TextAlign.center,style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('Pulse Trading Intelligence',textAlign:TextAlign.center,style:TextStyle(color:AbsColors.muted)),const SizedBox(height:20),AbsCard(child:Column(children:[const KeyValueRow('Mobile version','${AppConfig.mobileVersion}+${AppConfig.mobileBuild}'),KeyValueRow('Backend build',session.backendBuild),KeyValueRow('API base',AppConfig.apiBaseUrl),KeyValueRow('Market source',JsonTools.text(session.appBootstrap['market_data_source'],'ABS central database')),KeyValueRow('Target refresh','${session.marketRefreshSeconds} seconds')]))]));}}

class ChangePasswordScreen extends StatefulWidget {const ChangePasswordScreen({super.key});@override State<ChangePasswordScreen> createState()=>_ChangePasswordScreenState();}
class _ChangePasswordScreenState extends State<ChangePasswordScreen>{final current=TextEditingController(),password=TextEditingController(),confirm=TextEditingController();bool busy=false,hide=true;@override void dispose(){current.dispose();password.dispose();confirm.dispose();super.dispose();}Future<void>_save()async{if(password.text.length<8||password.text!=confirm.text){showSnack(context,password.text!=confirm.text?'Passwords do not match.':'Use at least 8 characters.',error:true);return;}setState(()=>busy=true);try{await SessionScope.of(context).api.patch('/profile',body:{'current_password':current.text,'password':password.text,'password_confirmation':confirm.text});if(mounted){showSnack(context,'Password updated.');Navigator.of(context).pop();}}on ApiException catch(e){if(mounted)showSnack(context,e.message,error:true);}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext context)=>AbsPage(title:'Change Password',subtitle:'Protect your ABS account',child:ListView(children:[TextField(controller:current,obscureText:true,decoration:const InputDecoration(labelText:'Current password')),const SizedBox(height:10),TextField(controller:password,obscureText:hide,decoration:InputDecoration(labelText:'New password',helperText:'8+ characters with upper/lower case and a number.',suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility_outlined:Icons.visibility_off_outlined)))),const SizedBox(height:10),TextField(controller:confirm,obscureText:true,decoration:const InputDecoration(labelText:'Confirm new password')),const SizedBox(height:14),ElevatedButton(onPressed:busy?null:_save,child:Text(busy?'Updating...':'Update password'))]));}
