@extends('admin.layout')
@section('title','Latest Market Prices — ABS Admin')
@section('heading','Latest Market Prices')
@section('description','Current prices stored in the ABS shared market database.')
@section('content')
@include('admin.pulse.workflow.step-head',['step'=>2,'title'=>'Latest Market Prices','subtitle'=>'Confirm that ABS is working with fresh market data before reviewing scans.'])
<section class="wf-status-strip"><div><span>Feed status</span><b class="{{ ($health['feed_status']??'')==='healthy'?'good':'warn' }}">{{ strtoupper($health['feed_status']??'offline') }}</b></div><div><span>Last sync</span><b>{{ $lastRun?->completed_at?->format('d M · H:i:s') ?? 'Never' }}</b></div><div><span>Markets stored</span><b>{{ number_format((int)($health['latest_price_symbols']??0)) }}</b></div><div><span>Price age</span><b>{{ isset($health['price_age_seconds']) ? number_format((int)$health['price_age_seconds']).' sec' : '—' }}</b></div><form method="POST" action="{{ route('admin.market-data.refresh') }}">@csrf<button class="button button-ghost">Refresh Now</button></form></section>
<section class="wf-panel wf-table-panel"><div class="wf-panel-head"><div><span class="wf-kicker">CURRENT DATABASE</span><h2>Latest stored price by market</h2></div><form class="wf-search" method="GET"><input name="q" value="{{ $q }}" placeholder="Search BTCUSDT"><button>Search</button></form></div><div class="wf-table-wrap"><table class="wf-table"><thead><tr><th>Market</th><th>Price</th><th>24h</th><th>24h High</th><th>24h Low</th><th>Observed</th><th>Source</th></tr></thead><tbody>@forelse($prices as $price)<tr><td><b>{{ $price->symbol }}</b></td><td>{{ number_format((float)$price->price,8) }}</td><td><span class="{{ (float)$price->change_percent_24h>=0?'good':'bad' }}">{{ (float)$price->change_percent_24h>=0?'+':'' }}{{ number_format((float)$price->change_percent_24h,2) }}%</span></td><td>{{ number_format((float)$price->high_24h,8) }}</td><td>{{ number_format((float)$price->low_24h,8) }}</td><td><b>{{ $price->observed_at?->format('H:i:s') ?? '—' }}</b><small>{{ $price->observed_at?->diffForHumans() }}</small></td><td>{{ str($price->source)->replace('_',' ')->title() }}</td></tr>@empty<tr><td colspan="7"><div class="wf-empty">No prices stored yet. Run a market refresh.</div></td></tr>@endforelse</tbody></table></div><div class="wf-pagination">{{ $prices->links('vendor.pagination.abs-admin') }}</div></section>
@endsection
