@extends('admin.layout')
@section('title','Paper Trades — ABS Admin')
@section('heading','Paper Trades')
@section('description','Signals that reached entry and became active research trades.')
@section('content')
@include('admin.pulse.workflow.step-head',['step'=>5,'title'=>'Paper Trades','subtitle'=>'Qualified signals appear here only after a later market cycle observes the entry price.'])
<section class="wf-mini-kpis wf-mini-kpis-five"><article><span>Waiting entry</span><b class="warn">{{ number_format($summary['waiting']) }}</b></article><article><span>Entered</span><b>{{ number_format($summary['entered']) }}</b></article><article><span>Open</span><b>{{ number_format($summary['open']) }}</b></article><article><span>Closed</span><b>{{ number_format($summary['closed']) }}</b></article><article><span>Long / Short</span><b>{{ number_format($summary['long']) }} / {{ number_format($summary['short']) }}</b></article></section>
<section class="wf-inline-note"><span class="wf-note-icon">↳</span><div><b>When does a signal become a paper trade?</b><small>ABS checks waiting signals on the next synchronized market cycle. If the market reaches the signal entry, the paper trade opens and TP/SL monitoring starts from the following candle.</small></div><div class="wf-note-actions"><span>{{ $profile['automatic_cycles'] ? 'Auto · '.$profile['effective_seconds'].' sec' : 'Manual mode' }}</span><form method="POST" action="{{ route('admin.pulse.strategy-dashboard.run-now') }}">@csrf<button type="submit">Run Next Cycle</button></form></div></section>
<section class="wf-panel wf-table-panel"><div class="wf-panel-head"><div><span class="wf-kicker">PAPER TRADE REGISTER</span><h2>Observed research entries</h2></div><form method="GET" class="wf-filter"><select name="state"><option value="">All trades</option><option value="open" {{ $state==='open'?'selected':'' }}>Open</option><option value="closed" {{ $state==='closed'?'selected':'' }}>Closed</option></select><select name="direction"><option value="">Long + Short</option><option value="LONG" {{ $direction==='LONG'?'selected':'' }}>Long</option><option value="SHORT" {{ $direction==='SHORT'?'selected':'' }}>Short</option></select><button>Apply</button></form></div><div class="wf-table-wrap"><table class="wf-table"><thead><tr><th>Entry time</th><th>Market</th><th>Side</th><th>Entry</th><th>Stop</th><th>Target</th><th>Status</th><th>Result</th><th></th></tr></thead><tbody>@forelse($trades as $trade)@php $levels=array_values((array)$trade->take_profit_levels); $target=$levels?end($levels):null; @endphp<tr><td>{{ $trade->entry_hit_at?->format('d M · H:i:s') ?? '—' }}</td><td><b>{{ $trade->symbol }}</b><small>{{ strtoupper($trade->timeframe) }}</small></td><td><span class="wf-pill is-{{ $trade->direction==='LONG'?'good':'bad' }}">{{ $trade->direction }}</span></td><td>{{ number_format((float)$trade->entry_price,8) }}</td><td>{{ number_format((float)$trade->stop_loss,8) }}</td><td>{{ $target?number_format((float)$target,8):'—' }}</td><td>{{ $trade->resolved_at?'Closed':'Open' }}</td><td><span class="wf-pill is-{{ $trade->outcome==='tp'?'good':($trade->outcome==='sl'?'bad':(in_array($trade->outcome,['ambiguous','expired_after_entry'])?'warn':'neutral')) }}">{{ strtoupper(str_replace('_',' ',(string)($trade->outcome ?: 'open'))) }}</span></td><td>@if($trade->signal?->scanner_run_id)<a class="wf-row-link" href="{{ route('admin.pulse.scan-audit.show',$trade->signal->scanner_run_id) }}">Trace →</a>@endif</td></tr>@empty<tr><td colspan="9"><div class="wf-empty">No signal has reached its entry yet. Waiting signals will be checked on the next market cycle.</div></td></tr>@endforelse</tbody></table></div><div class="wf-pagination">{{ $trades->links('vendor.pagination.abs-admin') }}</div></section>
@endsection
