@extends('admin.layout')
@section('title','Price Sync History — ABS Admin')
@section('heading','Price Sync History')
@section('description','Every market-price synchronization run and its captured price snapshot.')
@section('content')
@include('admin.pulse.workflow.step-head',['step'=>3,'title'=>'Price Sync History','subtitle'=>'Audit when prices were synchronized, how many markets updated and what each market price was.'])
<section class="wf-mini-kpis"><article><span>Total syncs</span><b>{{ number_format($summary['total']) }}</b></article><article><span>Completed</span><b class="good">{{ number_format($summary['completed']) }}</b></article><article><span>Failed</span><b class="{{ $summary['failed']?'bad':'' }}">{{ number_format($summary['failed']) }}</b></article><article><span>Price updates</span><b>{{ number_format($summary['prices']) }}</b></article></section>
<section class="wf-panel wf-table-panel"><div class="wf-panel-head"><div><span class="wf-kicker">SYNC RUNS</span><h2>Market-data history</h2></div><form method="GET" class="wf-filter"><select name="status" onchange="this.form.submit()"><option value="">All status</option>@foreach(['completed','failed','running'] as $s)<option value="{{ $s }}" {{ $status===$s?'selected':'' }}>{{ ucfirst($s) }}</option>@endforeach</select></form></div><div class="wf-table-wrap"><table class="wf-table"><thead><tr><th>Run</th><th>Started</th><th>Duration</th><th>Prices</th><th>Candle markets</th><th>Status</th><th></th></tr></thead><tbody>@forelse($runs as $run)<tr><td><b>#{{ $run->id }}</b><small>{{ data_get($run->summary,'cycle_mode','—') }}</small></td><td>{{ $run->started_at?->format('d M Y · H:i:s') ?? '—' }}</td><td>{{ $run->started_at&&$run->completed_at ? $run->started_at->diffInSeconds($run->completed_at).' sec' : '—' }}</td><td>{{ number_format((int)$run->prices_updated) }}</td><td>{{ number_format((int)$run->candle_symbols_updated) }}</td><td><span class="wf-pill is-{{ $run->status==='completed'?'good':($run->status==='failed'?'bad':'neutral') }}">{{ strtoupper($run->status) }}</span></td><td><a class="wf-row-link" href="{{ route('admin.pulse.price-history.show',$run) }}">Open prices →</a></td></tr>@empty<tr><td colspan="7"><div class="wf-empty">No sync history yet.</div></td></tr>@endforelse</tbody></table></div><div class="wf-pagination">{{ $runs->links('vendor.pagination.abs-admin') }}</div></section>
@endsection
