@extends('admin.layout')
@section('title','Price Sync #'.$marketRun->id.' — ABS Admin')
@section('heading','Price Sync #'.$marketRun->id)
@section('description','Exact market snapshot captured during this synchronization run.')
@section('content')
@include('admin.pulse.workflow.step-head',['step'=>3,'title'=>'Price Sync #'.$marketRun->id,'subtitle'=>'Exact per-market prices stored with this sync run.'])
<section class="wf-status-strip"><div><span>Status</span><b class="{{ $marketRun->status==='completed'?'good':'warn' }}">{{ strtoupper($marketRun->status) }}</b></div><div><span>Started</span><b>{{ $marketRun->started_at?->format('d M Y · H:i:s') ?? '—' }}</b></div><div><span>Completed</span><b>{{ $marketRun->completed_at?->format('d M Y · H:i:s') ?? '—' }}</b></div><div><span>Prices</span><b>{{ number_format((int)$marketRun->prices_updated) }}</b></div><a class="button button-ghost" href="{{ route('admin.pulse.price-history') }}">Back to History</a></section>
<section class="wf-panel wf-table-panel"><div class="wf-panel-head"><div><span class="wf-kicker">CAPTURED SNAPSHOT</span><h2>Market prices in this run</h2></div><span class="wf-chip">{{ number_format($snapshot->count()) }} records</span></div>@if($snapshot->isEmpty())<div class="wf-empty wf-empty-large">Exact per-market snapshots are stored for syncs created from ABS V15.4.0 onward. This older run only contains aggregate counts.</div>@else<div class="wf-table-wrap"><table class="wf-table"><thead><tr><th>Market</th><th>Price</th><th>24h</th><th>High</th><th>Low</th><th>Observed</th></tr></thead><tbody>@foreach($snapshot as $row)<tr><td><b>{{ $row['symbol'] ?? '—' }}</b></td><td>{{ number_format((float)($row['price']??0),8) }}</td><td><span class="{{ (float)($row['change_percent_24h']??0)>=0?'good':'bad' }}">{{ (float)($row['change_percent_24h']??0)>=0?'+':'' }}{{ number_format((float)($row['change_percent_24h']??0),2) }}%</span></td><td>{{ number_format((float)($row['high_24h']??0),8) }}</td><td>{{ number_format((float)($row['low_24h']??0),8) }}</td><td>{{ !empty($row['observed_at']) ? \Illuminate\Support\Carbon::parse($row['observed_at'])->format('H:i:s') : '—' }}</td></tr>@endforeach</tbody></table></div>@endif</section>
@endsection
