@extends('admin.layout')
@section('title','Strategy Performance — ABS Admin')
@section('heading','Strategy Performance')
@section('description','Compare every strategy by win/loss evidence and risk-normalized result.')
@section('content')
@include('admin.pulse.workflow.step-head',['step'=>7,'title'=>'Strategy Performance','subtitle'=>'Identify which strategies improve results and which need more evidence or review.'])
<div class="wf-range-tabs wf-top-tabs"><a class="{{ $range==='1d'?'active':'' }}" href="?range=1d">Today</a><a class="{{ $range==='7d'?'active':'' }}" href="?range=7d">7D</a><a class="{{ $range==='30d'?'active':'' }}" href="?range=30d">30D</a><a class="{{ $range==='90d'?'active':'' }}" href="?range=90d">90D</a></div>
<section class="wf-mini-kpis"><article><span>Strategies tracked</span><b>{{ number_format($rows->count()) }}</b></article><article><span>Positive evidence</span><b class="good">{{ number_format($positive) }}</b></article><article><span>Needs review</span><b class="{{ $review?'bad':'' }}">{{ number_format($review) }}</b></article><article><span>Best current evidence</span><b>{{ $top['name'] ?? 'Collecting' }}</b></article></section>
<section class="wf-panel wf-table-panel"><div class="wf-panel-head"><div><span class="wf-kicker">STRATEGY LEADERBOARD</span><h2>Win / loss and profitability evidence</h2></div><a href="{{ route('admin.pulse.strategies') }}">Manage strategy catalog →</a></div><div class="wf-table-wrap"><table class="wf-table"><thead><tr><th>#</th><th>Strategy</th><th>Signals</th><th>Win / Loss</th><th>Win rate</th><th>Net R</th><th>Model return</th><th>Reliability</th><th>Assessment</th></tr></thead><tbody>@forelse($rows as $row)@php($assessment=$row['decisive']<5?'Collecting':($row['net_r']>0?'Positive':'Review'))<tr><td><span class="wf-rank">{{ $loop->iteration }}</span></td><td><b>{{ $row['name'] }}</b><small>{{ $row['enabled']?'Enabled':'Disabled' }} · {{ $row['decisive'] }} decisive</small></td><td>{{ number_format($row['signals']) }}</td><td><span class="good">{{ $row['tp'] }}</span> / <span class="bad">{{ $row['sl'] }}</span></td><td><b>{{ $row['win_rate']===null?'—':number_format($row['win_rate'],1).'%' }}</b></td><td><b class="{{ $row['net_r']>=0?'good':'bad' }}">{{ ($row['net_r']>=0?'+':'').number_format($row['net_r'],2) }}R</b></td><td>{{ $row['model_return_pct']===null?'—':(($row['model_return_pct']>=0?'+':'').number_format($row['model_return_pct'],2).'%') }}</td><td>{{ $row['reliability']===null?'—':number_format($row['reliability'],1).'%' }}</td><td><span class="wf-pill is-{{ $assessment==='Positive'?'good':($assessment==='Review'?'bad':'neutral') }}">{{ strtoupper($assessment) }}</span></td></tr>@empty<tr><td colspan="9"><div class="wf-empty">No strategy evidence yet.</div></td></tr>@endforelse</tbody></table></div></section>
@endsection
