@extends('admin.layout')
@section('title','Private Investor Portfolio Reports — ABS Admin')
@section('heading','Portfolio Reports')
@section('description','Investor-by-investor local portfolio reporting with consolidated USD administration values.')
@section('page-actions')<a class="pi-btn" href="{{ route('admin.private-investors.reports.export') }}">Export CSV</a><a class="pi-btn" href="{{ route('admin.private-investors.overview') }}">Portfolio Overview</a>@endsection
@section('content')
<section class="pi-shell pi-reports-v1567">
    <article class="pi-card"><form class="pi-filter-row" method="GET"><label>Find investor<input name="q" value="{{ request('q') }}" placeholder="Name or email"></label><button class="pi-btn primary">Search</button>@if(request('q'))<a class="pi-btn" href="{{ route('admin.private-investors.reports') }}">Clear</a>@endif</form></article>
    <article class="pi-card"><div class="pi-card-head"><div><h2>Investor Performance Matrix</h2><span>Generated {{ $generatedAt->format('d M Y · H:i') }}</span></div></div><div class="pi-table-wrap"><table class="pi-table pi-report-matrix"><thead><tr><th>Investor</th><th>Investor Currency</th><th>Investor Principal</th><th>Reported Capital</th><th>Profit Paid / Net P&L</th><th>Admin USD Accounting</th><th>Realized FX</th><th>Return</th><th>MTD Provisional</th><th>Monthly Target</th><th>Progress</th><th>Requests</th><th>Last Statement</th><th></th></tr></thead><tbody>
    @forelse($matrix as $row)@php($a=$row['account'])<tr><td><b>{{ $a->user?->name }}</b><small>{{ $a->user?->email }}</small></td><td>{{ $a->currency }}</td><td>{{ $a->currency }} {{ number_format((float)$a->net_contributions,2) }}</td><td><b>{{ $a->currency }} {{ number_format((float)$a->current_value,2) }}</b><small>{{ $a->valuation_date?->format('d M Y') ?: 'No valuation date' }}</small></td><td class="{{ (float)$a->total_profit>=0?'pi-positive':'pi-negative' }}">{{ $a->currency }} {{ number_format((float)$a->total_profit,2) }}</td><td><b>USD {{ number_format($row['net_contributions_usd'],2) }} principal</b><small>Reported capital USD {{ number_format($row['current_value_usd'],2) }} · Profit paid USD {{ number_format($row['profit_paid_usd'],2) }} · Net P&L USD {{ number_format($row['total_profit_usd'],2) }}</small></td><td class="{{ $row['realized_fx_gain_loss_usd']>=0?'pi-positive':'pi-negative' }}">{{ $row['realized_fx_gain_loss_usd']>=0?'+':'' }}USD {{ number_format($row['realized_fx_gain_loss_usd'],2) }}</td><td class="{{ $row['return']>=0?'pi-positive':'pi-negative' }}">{{ number_format($row['return'],2) }}%</td><td>{{ $a->currency }} {{ number_format($row['mtd'],2) }}</td><td>{{ $a->currency }} {{ number_format($row['target'],2) }}</td><td><div class="pi-progress compact"><i style="width:{{ min(100,max(0,$row['progress'])) }}%"></i></div><small>{{ number_format($row['progress'],1) }}%</small></td><td>{{ $row['open_requests'] }}</td><td>{{ $row['last_statement']?->statement_month?->format('M Y') ?: '—' }}</td><td><a class="pi-mini-btn" href="{{ route('admin.private-investors.show',$a) }}">Open</a></td></tr>@empty<tr><td colspan="14">No investor accounts found.</td></tr>@endforelse
    </tbody></table></div>{{ $accounts->links() }}</article>
    <div class="pi-sensitive-note"><b>Reporting basis</b><span>Investor-facing records remain in the assigned account currency. Admin USD principal uses locked investment-date basis. Capital withdrawals return the original investor-currency amount and separately record Admin realized FX gain/loss; provisional monthly progress is shown in the investor currency and converted for Admin reporting without revaluing investor principal.</span></div>
</section>
@endsection
