@extends('admin.layout')
@section('title','Investor Requests — ABS Admin')
@section('heading','Investor Requests')
@section('description','Review additional investment, withdrawal and portfolio review requests.')
@section('content')
<section class="pi-shell"><div class="pi-note"><strong>Request workflow:</strong> Review the request, confirm the funds or payout outside the request record, record the matching portfolio transaction, then mark the request completed.</div><div class="pi-grid"><article class="pi-stat"><small>Submitted</small><strong>{{ $counts['submitted'] }}</strong></article><article class="pi-stat"><small>Under Review</small><strong>{{ $counts['under_review'] }}</strong></article><article class="pi-stat"><small>Approved</small><strong>{{ $counts['approved'] }}</strong></article><article class="pi-stat"><small>Completed</small><strong>{{ $counts['completed'] }}</strong></article></div>
<form class="pi-card pi-form" method="GET"><div class="pi-form-row"><label>Status<select name="status"><option value="">All statuses</option>@foreach(['submitted','under_review','approved','declined','completed','cancelled'] as $v)<option value="{{ $v }}" @selected(request('status')===$v)>{{ ucwords(str_replace('_',' ',$v)) }}</option>@endforeach</select></label><label>Request type<select name="type"><option value="">All types</option>@foreach(['add_investment','withdrawal','portfolio_review'] as $v)<option value="{{ $v }}" @selected(request('type')===$v)>{{ ucwords(str_replace('_',' ',$v)) }}</option>@endforeach</select></label></div><div><button class="pi-btn">Apply Filter</button></div></form>
@forelse($requests as $r)<article class="pi-card"><div class="pi-card-head"><h2>{{ $r->user?->name }} · {{ ucwords(str_replace('_',' ',$r->type)) }}</h2><span class="pi-status {{ $r->status }}">{{ str_replace('_',' ',$r->status) }}</span></div><div class="pi-summary-band"><div><small>Amount</small><strong>{{ $r->amount ? $r->currency.' '.number_format($r->amount,2) : 'Not applicable' }}</strong></div><div><small>Submitted</small><strong>{{ $r->created_at->format('d M Y · H:i') }}</strong></div><div><small>Investor</small><strong>{{ $r->user?->email }}</strong></div></div>@if($r->message)<div class="pi-note">{{ $r->message }}</div>@endif<form method="POST" action="{{ route('admin.private-investors.requests.update',$r) }}" class="pi-form" style="margin-top:12px">@csrf @method('PUT')<div class="pi-form-row"><label>Status<select name="status">@foreach(['submitted','under_review','approved','declined','completed'] as $v)<option value="{{ $v }}" @selected($r->status===$v)>{{ ucwords(str_replace('_',' ',$v)) }}</option>@endforeach</select></label><label>Admin note<input name="admin_note" value="{{ $r->admin_note }}" placeholder="Visible to investor"></label></div><div class="pi-actions"><button class="pi-btn primary">Update Request</button>@if($r->account)<a class="pi-btn" href="{{ route('admin.private-investors.show',$r->account) }}">Open Portfolio</a>@endif</div></form>@if($r->user)<form method="POST" action="{{ route('admin.support.start',$r->user) }}" style="margin-top:8px">@csrf<button class="pi-btn" type="submit">Message Investor</button></form>@endif</article>@empty<div class="pi-empty">No requests match the selected filters.</div>@endforelse{{ $requests->links() }}</section>
@endsection
